- src/components/icon/icon.stories.js
feat/all-icons-story
- TODO: Copy the code icon when click.
> feat(docs): added all icons story

- src/components.d.ts
- src/components/button/button.scss
- src/components/button/button.spec.ts
- src/components/button/button.stories.jsx
- src/components/button/button.tsx
- src/components/button/readme.md
- src/components/icon/readme.md
ISSUES CLOSED: #9
feature/button_disable
> feat(component): altered button disable scss

- src/components/button/button.scss
- src/components/card-color/card-color.scss
- src/components/card-color/card-color.stories.jsx
- src/globals/_colors.scss
- src/globals/export.scss
> fix(component): fixted grammar

- src/components/card-color/card-color.stories.jsx
- src/globals/_colors.scss
> feat(component): altered suit color

- src/components.d.ts
- src/components/button/button.tsx
- src/components/button/readme.md
> feat(component): added event click on button

- src/components/input/input.scss
> fix(component): altered color

- src/components.d.ts
- src/components/button/button.tsx
- src/components/button/readme.md
- src/components/input/inputs.tsx
> fix(component): fix eslint

- readme.md
> docs(docs): add readmed with examples

- src/components/checkbox/checkbox.scss
> feat(component): adjust checkbox size

- src/components.d.ts
- src/components/button/button.scss
- src/components/button/button.stories.jsx
- src/components/button/button.tsx
- src/components/button/readme.md
feat/rename_second_prop
Just renaming second to secondary.
> feat(component): renaming from second to secondary on button

- package.json
- src/components/checkbox/checkbox.scss
- src/components/radio/radio.scss
- src/index.html
> fix(component): add background color

- src/components/icon/icon.tsx
- src/components/select-option/readme.md
- src/components/select-option/select-option.stories.jsx
- src/components/select-option/select-option.tsx
- src/components/select/readme.md
- src/components/select/select.stories.jsx
- src/components/select/select.tsx
- src/index.html
> feat(component): separate select with select option

- src/components/input/input.scss
- src/components/input/input.tsx
- src/components/menu-list-item/menu-list-item.scss
- src/components/menu-list-item/menu-list-item.tsx
> feat(component): added host in menu list and input

- src/components/button/button.tsx
- src/components/icon/icon.tsx
- src/components/menu-list-item/menu-list-item.tsx
> fix(component): menu list item error

- src/components/menu-list/menu-list.scss
- src/components/menu-list/menu-list.tsx
> fix(component): ajust menu list size

- src/components/checkbox/checkbox.tsx
- src/components/radio/radio.tsx
> fix(component): added reflectattr on data entries

- src/components/select/select.stories.jsx
- src/components/select/select.tsx
- src/index.html
> fix(component): binding select value

- src/components.d.ts
- src/components/icon-button/icon-button.scss
- src/components/icon-button/icon-button.stories.jsx
- src/components/icon-button/icon-button.tsx
- src/components/icon-button/readme.md
- src/components/icon/icon-interface.ts
- src/components/icon/readme.md
- src/index.html
> feat(component): added icon button

- src/components.d.ts
- src/components/alert/alert-header/alert-header.scss
- src/components/alert/alert-header/alert-header.spec.tsx
- src/components/alert/alert-header/alert-header.tsx
- src/components/alert/alert.stories.jsx
- src/components/button/button.stories.jsx
- src/components/button/button.tsx
- src/components/button/readme.md
feature/alert_adjustments
Updating with the changes requested by the PD and making the storybook all customizable.
> feat: storybook improvements and adjustments

- src/components.d.ts
- src/components/button/button.e2e.ts
- src/components/button/button.stories.jsx
- src/components/button/button.tsx
- src/components/button/readme.md
> feat: adding types to button and fixing submit

- package.json
- src/components.d.ts
- src/components/icon/icon.stories.jsx
- src/components/icon/readme.md
- src/components/typo/readme.md
- src/components/warning/readme.md
- src/components/warning/warning.scss
- src/components/warning/warning.spec.tsx
- src/components/warning/warning.stories.jsx
- src/components/warning/warning.tsx
create warning element on design system
> feat: create warning element

- src/components/icon/icon.scss
> fix(icon): added min width and height

- package.json
- src/components/icon/icon.stories.jsx
> fix(icon): added new icon

- src/components/input/input.tsx
> feat(component): add focus on input

- src/components/toast/toast.tsx
> feat: modifying toast interface

- src/components.d.ts
- src/components/button/button.scss
- src/components/button/button.spec.ts
- src/components/button/button.stories.jsx
- src/components/button/button.tsx
- src/components/button/readme.md
- src/components/loading-spinner/loading-spinner.scss
- src/components/loading-spinner/loading-spinner.tsx
- src/components/loading-spinner/readme.md
- src/components/loading-spinner/tests/loading-spinner.spec.ts
- src/components/toast/readme.md
Load spinner component, used inside bds-button by the bds-loading attribute
> feat: adding load spinner on bds-button

- src/components/toast-container/toast-container.scss
- src/components/toast/toast.scss
feature/toast_responsive
Adding media queries to make the toast responsive
> feat: adding toast media query

- src/components/toast/toast.tsx
> feat: modifying toast open order

- src/components.d.ts
- src/components/input-chips/tests/input-chips.e2e.ts
- src/components/input/input.tsx
- src/components/input/tests/__snapshots__/input.spec.ts.snap
- src/components/input/tests/input.e2e.ts
- src/components/input/tests/input.spec.ts
> feat: add shadow to input again

- src/components/input-chips/input-chips.tsx
> fix(component): add event blur

- src/components.d.ts
- src/components/input-chips/input-chips.tsx
- src/components/input-chips/readme.md
- src/components/input/input.tsx
> fix(component): attr reflect

- src/components.d.ts
- src/components/input/input.scss
- src/components/input/input.tsx
- src/components/input/tests/input.e2e.ts
- src/components/toast/toast.scss
- Increase margin-top on input error-messages
- Added space between the toast text and button
- Fix external input validation (danger and error-message)
> feat: fix input validation, error-message margin, toast margin

- src/components/input/input.scss
Changes:
- Fix border on firefox
- Fix placeholder color
> fix input border on firefox and placeholder color

- src/components.d.ts
- src/components/button/button.scss
- src/components/button/button.tsx
- src/components/button/readme.md
- src/components/input/tests/__snapshots__/input.spec.ts.snap
- src/components/toast-container/tests/__snapshots__/toast-container.spec.tsx.snap
- src/components/toast/tests/__snapshots__/toast.spec.tsx.snap
- src/globals/_colors.scss
Add Faebook variant for button to use blip-ds in accordance with Facebook user experience design.
https://developers.facebook.com/docs/facebook-login/userexperience/
> Add Facebook variant for button

- src/globals/_mixins.scss
> fix: scroll style

- src/components/button/button.scss
- src/components/loading-spinner/loading-spinner.tsx
- src/components/loading-spinner/tests/loading-spinner.spec.ts
> fix: loading spinner positioning

- src/components/alert/alert.scss
- src/globals/_zindex.scss
> feat: update z-index variables

- src/components/input-chips/input-chips.tsx
feature/clear-input-chips-value
> feat: clear input chips value on clear method

- src/components/selects/select-chips/select-chips.tsx
fix/select_chips_case_sensitive
> feat(component): serch with case insensitive

- src/components/selects/select-chips/select-chips.tsx
- src/index.html
> fix(component): add isValid method in select chips

- src/components/input-chips/input-chips.tsx
- src/components/input-chips/readme.md
- src/index.html
1. Not accept duplicated per default
> fix(component): not accept duplicated per default

- src/components.d.ts
- src/components/banner/banner.scss
- src/components/banner/banner.tsx
- src/components/banner/readme.md
feature/186480_banner_background_prop
> feat: add background prop to banner component

- stencil.config.ts
bugfix/202053_old_browser_build
> feat: set configs to generate build to old browsers

- package.json
- src/components/input-phone-number/input-phone-number.scss
- src/components/input-phone-number/input-phone-number.tsx
- src/components/select-option/select-option.scss
Fixing Input phone number background and flag
> fix: fixing input phone number flag and background

- src/components/input-phone-number/input-phone-number.scss
- src/components/input-phone-number/input-phone-number.tsx
fixing input phone number flag overwriting error message
> fix: fixing input phone number flag overwriting error message

- src/globals/_colors.scss
- src/globals/export.scss
add new colors to be used in Blip Portal
> add new colors

- package.json
- src/globals/_colors.scss
Adding colors and getting from Blip Tokens.
> feat(colors): adding gradient colors to blip ds

- src/components/select-option/select-option.scss
fix background on select-option click
> fix: fix select bg color on focus

- src/components/input-phone-number/input-phone-number.scss
- src/components/stepper/stepper.tsx
Fixed stepper initialization and fixed input phone number hover area
> fix: stepper childs and input phone number hover

- src/components/input-chips/input-chips.tsx
Fix input-chips emitting change-event on changing internalChips
> fix(component): fix input-chips change event

- blip-ds-react/src/components.ts
- package.json
- src/components.d.ts
- src/components/bds-switch/bds-switch.scss
- src/components/bds-switch/bds-switch.stories.jsx
- src/components/bds-switch/bds-switch.tsx
- src/components/bds-switch/readme.md
- src/components/bds-switch/test/bds-switch.e2e.ts
- src/components/bds-switch/test/bds-switch.spec.tsx
- src/index.html
Switch component developed based on button and checkbox.
- three sizes
- two check options
- two option to enable
> feat(switch): new component

- src/components/modal/modal.stories.jsx
> fix(modal): fix modal close button (story book).

- src/components.d.ts
- src/components/selects/select-chips/readme.md
- src/components/selects/select-chips/select-chips.tsx
This merge creates a method to get the chips on the select-chips component
> feat(select-chips): create a method to get the internal chips

- src/components/autocomplete/autocomplete.stories.jsx
- src/components/autocomplete/autocomplete.tsx
-Fixed the event onFocusOut to onFocusout on div
> fix(autocomplete): onFocusout event fixed

- src/components/autocomplete/autocomplete.tsx
Fix event fired on change input
> fix(autocomplete): adjust event change input

- package.json
> Revert "feat(build): version jest"

- src/components.d.ts
- src/components/chip-clickable/chip-clickable.tsx
- src/components/chip-clickable/readme.md
- src/components/chip-selected/chip-selected.tsx
- src/components/chip-selected/readme.md
> Revert "feat(chips): add data test in chip clickable and selected"

- package.json
> Revert "feat(checkbox): fixing to build"

- src/components/icon/icon.stories.jsx
> Revert "feat(icons): add priorization icon"

- src/components/tabs/tab-group.scss
changed overflow from auto to none
> overflow fix on tabsGroup

- src/globals/theme/theme-light.scss
Updates on lightmode colors for surfaces and contents
> Light mode colors update
